title: Blog do Juan
description: Mais um desses blogs sobre tecnologia.
author: Juan
avatar: /logo.png
location: Rio de Janeiro - BR
#email: my first name.franca@gmail.com
subscribe: false

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
#twitter:
#  username: ngzhio
#  card: summary
logo: logo.png
social:
  name: Juan
  links:
#    - https://twitter.com/ngzhio
#    - https://www.facebook.com/ngzhio
    - https://github.com/jfrbr
lang: en
